# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.java.home=C:\\Users\\rebel\\jdk\\jdk-25.0.4

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.worldpresetpack
archives_base_name=worldpresetpack

# Dependencies
fabric_version=0.156.0+26.2
